class en:
    from_o = " from origin "
    from_d = " from destiny "
    pick = "pick"
    drop = "drop"
    to_pick = "pick"
    to_drop = "drop"
    rpt = "repeat"
    ok = " okey"
    bx= ""
    into_d = " into destiny "
    done = "done"

    hola = " Hi, I am your voice assistant"
    algo = " Say something!"
    rec_num = " No number has been recognized"
    srry = " I am sorry, I haven't understood what you said"
    creo = " I think you said: "
    back = "back"
    there_not = "There are not"
    there = " there "
    task_cant = " The task cant be completed "
    task_end = " The task has been finished"
    orig = "origin"
    dest = "destiny"
    unders = "understand"

    problema = "You had a problem"
    connex = "Sorry, I cant connect to my system"



class es:
    from_o = " de origen"
    from_d = " de destino"
    pick =  "coger"
    drop = "dejar"
    to_pick = "cojo"
    to_drop = "dejo"
    rpt = "repite"
    ok = " vale"
    bx = ""
    into_d = " en el destino "
    back = "donde estaba"

    hola = " Hola soy tu asistente de voz"
    algo = " Hola, Di algo!"
    rec_num = " No se ha reconocido ningun numero"
    srry = " Person, no he entendido lo que has dicho"
    creo = " Creo que has dicho: "

    task_cant = "La tarea no puede ser completada"
    task_end = "Tarea completada"

    there_not = " No hay "
    there = " alli "
    orig = "origen"
    dest = "destino"
    unders = "entendido"
    done = "hecho"
    problema = "Has tenido un problema"
    connex = "Perdón, no puedo conectarme a mi servidor"